# Generated by Django 2.1.4 on 2019-01-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='send_via',
            field=models.IntegerField(choices=[(1, 'SMS'), (2, 'E-Mail'), (3, 'WhatsAPP')], default=1),
        ),
    ]
